spring:
  application:
    name: gateway

server:
  port: 8080
  servlet:
    context-path: /gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka/

zuul:
  sensitive-headers: Cookie
  
jwt:
  config:
    login-url: /auth/login